### PR TITLE
Upgrade Visual Studio solution

### PR DESCRIPTION
**Pull request by EccentricVamp**
There have been a number of changes to the Visual Studio solution and project format since 2010. To make the development experience in this repo easier for newer Windows developers (including myself), I've done some housekeeping to bring the project inline with the latest versions of Visual Studio.

### CODE REVIEW

**Comment by EccentricVamp** [comment]
Let me know if you need more info or test outputs or anything. I couldn't find any contribution guidelines so I'm not sure what the process is for pull requests in this repo.

**Comment by joachimmetz** [comment]
@EccentricVamp this should not be needed, this project uses https://github.com/libyal/vstools for converting between versions for automated testing and VS studio should be able to allow you to update the solution files.

**Comment by joachimmetz** [comment]
A first attempt at automating the build even further https://github.com/libyal/libnsfdb/blob/main/build.ps1

**Comment by EccentricVamp** [comment]
Okay. I don't use Python, but I'll install and try to get it working.

I was following the documentation here https://github.com/libyal/libnsfdb/wiki/Building#using-microsoft-visual-studio, which does not reference vstools. Is there newer documentation that I should be following?

While Visual Studio is able to update solution files, it adds a significant number of artifacts that I don't think should be commited, hence the changes to the .gitignore file.

**Comment by joachimmetz** [comment]
vstools is something I wrote myself specifically for libyal projects, seeing in the past VS had a CLI upgrade tool but only in the commercial version, so could not really use this on CI environments. 

> Is there newer documentation that I should be following?

Nope, the build.ps1 script and appveyor.yml config might give you the necessary pointers.

> While Visual Studio is able to update solution files, it adds a significant number of artifacts that I don't think should be commited, hence the changes to the .gitignore file.

yeah only sln and vcxproj files are needed, rest can be ignored, but you create the newer files in a separate directory just for development. Technically the current files get generated from the autoconf/automake configurations.

**Comment by joachimmetz** [comment]
Will not merge the changes since the project has other ways of upgrading VS solution file versions.

**Pull request closed without merging**
